#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ascl1_gmm_high_low_analysis.py
================================
GMM-based Ascl1 High vs Low classification and downstream analysis
in female hepatocytes (single-cell multiome RNA).

Sections
--------
1.  Load data
2.  GMM classification — Ascl1 High vs Low (female hepatocytes)
3.  GMM High/Low count dot plots (selected celltype2 subtypes)
4.  Differential expression — Ascl1-High vs Ascl1-Low (Wilcoxon)
5.  GSEA — Reactome Pathways 2024
6.  GSEA dot plots — top 30 positive NES + top 30 negative NES
"""

import re
import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt
import seaborn as sns
import gseapy as gp
from sklearn.mixture import GaussianMixture
from pathlib import Path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — Load Data
# ═══════════════════════════════════════════════════════════════════════════════

# Path to the WNN-integrated single-cell RNA object (h5ad format).
# Generated by the ArchR preprocessing pipeline → schard h5ad conversion.
# Contains cells from 5 age groups across both sexes with celltype/celltype2.
h5ad_path = "/data/sarkern2/multiome_liver/final_object/final_rna_wnn.h5ad"

# Output directories
fig_dir = Path("figures")
res_dir = Path("results")
fig_dir.mkdir(exist_ok=True)
res_dir.mkdir(exist_ok=True)

print("Loading data …")
adata = sc.read_h5ad(h5ad_path)
print(f"Loaded {adata.n_obs:,} cells × {adata.n_vars:,} genes")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — GMM Classification: Ascl1 High vs Low (Female Hepatocytes)
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("GMM CLASSIFICATION: Ascl1 High vs Low (Female Hepatocytes)")
print("=" * 60)

# ── Subset to female hepatocytes ─────────────────────────────────────────────
adata_fh = adata[
    (adata.obs["sex"].astype(str) == "female") &
    (adata.obs["celltype"].astype(str) == "Hepatocyte")
].copy()

assert adata_fh.n_obs > 0, "No female hepatocytes found"
assert "Ascl1" in adata_fh.var_names, "Ascl1 not found"
print(f"\nFemale hepatocytes: {adata_fh.n_obs:,}")

# ── Extract Ascl1 expression ─────────────────────────────────────────────────
gene = "Ascl1"
expr = adata_fh[:, gene].X
expr = expr.toarray().ravel() if not isinstance(expr, np.ndarray) else expr.ravel()
adata_fh.obs["Ascl1_expr"] = expr

# Cells with any detectable expression (> 0) are Ascl1-positive.
# The GMM is then fit ONLY to these Ascl1+ cells to distinguish
# "High" vs "Low" expressors — fitting to all cells would be dominated
# by the zero-inflation peak.
adata_fh.obs["Ascl1_positive"] = adata_fh.obs["Ascl1_expr"] > 0
adata_pos = adata_fh[adata_fh.obs["Ascl1_positive"]].copy()
print(f"Ascl1+ female hepatocytes: {adata_pos.n_obs:,} "
      f"({100 * adata_pos.n_obs / adata_fh.n_obs:.1f}%)")

# ── Fit 2-component Gaussian Mixture Model ───────────────────────────────────
# Why GMM? Single-cell expression of lowly-expressed TFs like Ascl1 is often
# bimodal among expressing cells — a "Low" population near the detection limit
# and a "High" population with genuine transcriptional activation.
# GMM provides a principled, probabilistic boundary between these two states.
# n_components=2: we expect exactly two expression modes (High and Low).
# random_state=0: ensures reproducibility.
expr_vals = adata_pos.obs["Ascl1_expr"].values.reshape(-1, 1)

gmm = GaussianMixture(
    n_components=2,
    random_state=0,
).fit(expr_vals)

clusters = gmm.predict(expr_vals)
means = gmm.means_.flatten()

# The cluster with the higher mean is labeled "High"
high_cluster = np.argmax(means)

adata_pos.obs["Ascl1_group"] = np.where(
    clusters == high_cluster, "High", "Low"
)

# ── Posterior probabilities ──────────────────────────────────────────────────
# These give the confidence of each cell's classification.
# prob_high > 0.9 means the cell is very confidently in the High group.
probs = gmm.predict_proba(expr_vals)
adata_pos.obs["prob_high"] = probs[:, high_cluster]
adata_pos.obs["prob_low"] = probs[:, 1 - high_cluster]

# ── AIC / BIC model selection ────────────────────────────────────────────────
# Compare 1-, 2-, and 3-component models. Lower AIC/BIC = better fit.
# If the 2-component model wins, it validates our assumption of bimodality.
gmm_1 = GaussianMixture(n_components=1, random_state=0).fit(expr_vals)
gmm_3 = GaussianMixture(n_components=3, random_state=0).fit(expr_vals)

# ── Print summary ────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("GMM RESULTS SUMMARY")
print("=" * 60)

low_count = (adata_pos.obs["Ascl1_group"] == "Low").sum()
high_count = (adata_pos.obs["Ascl1_group"] == "High").sum()

print(f"\n📊 GMM Classification:")
print(f"   Low group:  {low_count:,} cells ({100 * low_count / adata_pos.n_obs:.1f}%)")
print(f"   High group: {high_count:,} cells ({100 * high_count / adata_pos.n_obs:.1f}%)")

print(f"\n📊 GMM Cluster Parameters:")
print(f"   Low cluster mean:  {means[1 - high_cluster]:.3f}")
print(f"   High cluster mean: {means[high_cluster]:.3f}")
print(f"   Fold difference:   {means[high_cluster] / means[1 - high_cluster]:.2f}×")

print(f"\n📊 Expression Statistics by Group:")
for group in ["Low", "High"]:
    sub = adata_pos.obs[adata_pos.obs["Ascl1_group"] == group]["Ascl1_expr"]
    print(f"   {group}: mean={sub.mean():.3f}, median={sub.median():.3f}, "
          f"std={sub.std():.3f}, range=[{sub.min():.3f}, {sub.max():.3f}]")

print(f"\n📊 Model Selection (AIC/BIC):")
print(f"   {'Model':<15} {'AIC':>12} {'BIC':>12}")
print(f"   {'-' * 15} {'-' * 12} {'-' * 12}")
print(f"   {'1-component':<15} {gmm_1.aic(expr_vals):>12.1f} {gmm_1.bic(expr_vals):>12.1f}")
print(f"   {'2-component':<15} {gmm.aic(expr_vals):>12.1f} {gmm.bic(expr_vals):>12.1f}")
print(f"   {'3-component':<15} {gmm_3.aic(expr_vals):>12.1f} {gmm_3.bic(expr_vals):>12.1f}")

delta_aic = gmm_1.aic(expr_vals) - gmm.aic(expr_vals)
delta_bic = gmm_1.bic(expr_vals) - gmm.bic(expr_vals)
print(f"\n   ΔAIC (1 vs 2): {delta_aic:.1f} (2-component better)")
print(f"   ΔBIC (1 vs 2): {delta_bic:.1f} (2-component better)")

high_conf = ((adata_pos.obs["prob_high"] > 0.9) | (adata_pos.obs["prob_low"] > 0.9)).sum()
print(f"\n📊 Classification Confidence:")
print(f"   High confidence (prob > 0.9): {high_conf:,} cells "
      f"({100 * high_conf / adata_pos.n_obs:.1f}%)")

print(f"\n📊 GMM Groups by Age:")
age_gmm = pd.crosstab(
    adata_pos.obs["age"], adata_pos.obs["Ascl1_group"], margins=True
)
print(age_gmm.to_string())

print(f"\n📊 GMM Groups by Celltype2:")
ct2_gmm = pd.crosstab(
    adata_pos.obs["celltype2"], adata_pos.obs["Ascl1_group"], margins=True
)
print(ct2_gmm.to_string())
print("\n" + "=" * 60)

# ── Save results ─────────────────────────────────────────────────────────────
out_df = adata_pos.obs[["Ascl1_expr", "Ascl1_group", "prob_low", "prob_high"]]
out_df.to_csv(res_dir / "Ascl1_GMM_HighLow_female_hepatocytes.csv", index=True)
print(f"\n💾 Saved: {res_dir}/Ascl1_GMM_HighLow_female_hepatocytes.csv")

age_gmm_summary = adata_pos.obs.groupby(["age", "Ascl1_group"], observed=True).agg(
    count=("Ascl1_expr", "size"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_gmm_summary.to_csv(res_dir / "Ascl1_GMM_summary_by_age.csv", index=False)
print(f"💾 Saved: {res_dir}/Ascl1_GMM_summary_by_age.csv")

ct2_gmm_summary = adata_pos.obs.groupby(["celltype2", "Ascl1_group"], observed=True).agg(
    count=("Ascl1_expr", "size"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
ct2_gmm_summary.to_csv(res_dir / "Ascl1_GMM_summary_by_celltype2.csv", index=False)
print(f"💾 Saved: {res_dir}/Ascl1_GMM_summary_by_celltype2.csv")
print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — GMM High/Low Count Dot Plots (Selected Celltype2 Subtypes)
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("GMM HIGH/LOW DOTPLOT: Female Hepatocytes (Selected Subtypes)")
print("=" * 60)

# These 5 hepatocyte subtypes were selected because they represent the
# major zonation-related populations (periportal → pericentral) with
# sufficient Ascl1+ cells for meaningful High/Low comparisons.
keep_ct2 = ["Hep-07", "Hep-06", "Hep-04", "Hep-03", "Hep-02"]

adata_hep_f_ct2_pos = adata_pos[
    adata_pos.obs["celltype2"].isin(keep_ct2)
].copy()

print(f"\nAscl1+ female hepatocytes (selected celltype2): {adata_hep_f_ct2_pos.n_obs:,}")
print(f"\n📊 GMM Group Distribution:")
print(adata_hep_f_ct2_pos.obs["Ascl1_group"].value_counts())

# ── Ordered categories ───────────────────────────────────────────────────────
# Reversed age order (geriatric at top) for visual consistency with
# the aging trajectory when reading top-to-bottom.
age_order = ["geriatric", "pre_geriatric", "old", "mid_age", "young"]
celltype2_order = keep_ct2

adata_hep_f_ct2_pos.obs["age"] = pd.Categorical(
    adata_hep_f_ct2_pos.obs["age"], categories=age_order, ordered=True
)
adata_hep_f_ct2_pos.obs["celltype2"] = pd.Categorical(
    adata_hep_f_ct2_pos.obs["celltype2"], categories=celltype2_order, ordered=True
)

# ── Count tables ─────────────────────────────────────────────────────────────
age_ct = (
    adata_hep_f_ct2_pos.obs.groupby(["age", "Ascl1_group"], observed=True)
    .size().reset_index(name="cell_count")
)
ct2_ct = (
    adata_hep_f_ct2_pos.obs.groupby(["celltype2", "Ascl1_group"], observed=True)
    .size().reset_index(name="cell_count")
)

# ── Summary statistics ───────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("SUMMARY STATISTICS")
print("=" * 60)

total = adata_hep_f_ct2_pos.n_obs
high_count = (adata_hep_f_ct2_pos.obs["Ascl1_group"] == "High").sum()
low_count = (adata_hep_f_ct2_pos.obs["Ascl1_group"] == "Low").sum()

print(f"\n📊 Overall (Selected Subtypes):")
print(f"   Total Ascl1+ cells: {total:,}")
print(f"   High: {high_count:,} ({100 * high_count / total:.1f}%)")
print(f"   Low: {low_count:,} ({100 * low_count / total:.1f}%)")

print(f"\n📊 GMM Groups by Age:")
age_summary = adata_hep_f_ct2_pos.obs.groupby("age", observed=True).agg(
    total=("Ascl1_group", "size"),
    high=("Ascl1_group", lambda x: (x == "High").sum()),
    low=("Ascl1_group", lambda x: (x == "Low").sum()),
).reset_index()
age_summary["pct_high"] = 100 * age_summary["high"] / age_summary["total"]
age_summary["pct_low"] = 100 * age_summary["low"] / age_summary["total"]
print(age_summary.to_string(index=False))

print(f"\n📊 GMM Groups by Celltype2:")
ct2_summary = adata_hep_f_ct2_pos.obs.groupby("celltype2", observed=True).agg(
    total=("Ascl1_group", "size"),
    high=("Ascl1_group", lambda x: (x == "High").sum()),
    low=("Ascl1_group", lambda x: (x == "Low").sum()),
).reset_index()
ct2_summary["pct_high"] = 100 * ct2_summary["high"] / ct2_summary["total"]
ct2_summary["pct_low"] = 100 * ct2_summary["low"] / ct2_summary["total"]
ct2_summary = ct2_summary.sort_values("pct_high", ascending=False)
print(ct2_summary.to_string(index=False))

print(f"\n📊 Ascl1-High Cells: Age × Celltype2:")
high_only = adata_hep_f_ct2_pos[adata_hep_f_ct2_pos.obs["Ascl1_group"] == "High"]
crosstab = pd.crosstab(high_only.obs["age"], high_only.obs["celltype2"], margins=True)
print(crosstab.to_string())
print("\n" + "=" * 60)

# ── Dodge dot positions to prevent High/Low overlap ──────────────────────────
# Offset each group by ±0.15 on the x-axis so dots don't stack on top
# of each other at the same integer position.
dodge_map = {"Low": -0.15, "High": 0.15}

age_ct["x_pos"] = (age_ct["Ascl1_group"].map({"Low": 0, "High": 1})
                    + age_ct["Ascl1_group"].map(dodge_map))
ct2_ct["x_pos"] = (ct2_ct["Ascl1_group"].map({"Low": 0, "High": 1})
                    + ct2_ct["Ascl1_group"].map(dodge_map))

# ── Plot ─────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Panel 1 — Age
sns.scatterplot(
    data=age_ct, x="x_pos", y="age",
    size="cell_count", hue="cell_count",
    palette="Reds", sizes=(60, 550),
    edgecolor="black", linewidth=0.6, ax=axes[0],
)
axes[0].set_title("Ascl1 GMM High/Low — Age (Female Hepatocytes)", weight="bold")
axes[0].set_xticks([0, 1])
axes[0].set_xticklabels(["Low", "High"])
axes[0].set_xlabel("Ascl1 Group")
axes[0].set_ylabel("Age")
axes[0].set_xlim(-0.5, 1.5)
axes[0].margins(x=0.1)
axes[0].set_ylim(-0.4, len(age_order) - 0.6)
axes[0].margins(y=0.005)
axes[0].set_yticks(range(len(age_order)))
axes[0].set_yticklabels(age_order)
axes[0].legend_.remove()
axes[0].legend(title="Cell Count", bbox_to_anchor=(1.18, 0.5),
               loc="center left", frameon=True, fontsize=9)

# Panel 2 — Celltype2
sns.scatterplot(
    data=ct2_ct, x="x_pos", y="celltype2",
    size="cell_count", hue="cell_count",
    palette="Reds", sizes=(60, 550),
    edgecolor="black", linewidth=0.6, ax=axes[1],
)
axes[1].set_title("Ascl1 GMM High/Low — Celltype2 (Female Hepatocytes)", weight="bold")
axes[1].set_xticks([0, 1])
axes[1].set_xticklabels(["Low", "High"])
axes[1].set_xlabel("Ascl1 Group")
axes[1].set_ylabel("Celltype2")
axes[1].set_xlim(-0.5, 1.5)
axes[1].margins(x=0.1)
axes[1].set_ylim(-0.4, len(celltype2_order) - 0.6)
axes[1].margins(y=0.005)
axes[1].set_yticks(range(len(celltype2_order)))
axes[1].set_yticklabels(celltype2_order)
axes[1].legend_.remove()
axes[1].legend(title="Cell Count", bbox_to_anchor=(1.18, 0.5),
               loc="center left", frameon=True, fontsize=9)

plt.tight_layout()
plt.savefig(fig_dir / "Ascl1_GMM_HighLow_count_dotplots_female_hep_age_ct2.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/Ascl1_GMM_HighLow_count_dotplots_female_hep_age_ct2.pdf")

age_summary.to_csv(res_dir / "Ascl1_GMM_dotplot_summary_by_age.csv", index=False)
ct2_summary.to_csv(res_dir / "Ascl1_GMM_dotplot_summary_by_celltype2.csv", index=False)
print(f"💾 Saved summary CSVs → {res_dir}/")
print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4 — Differential Expression: Ascl1-High vs Ascl1-Low (Wilcoxon)
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("DIFFERENTIAL EXPRESSION: Ascl1-High vs Ascl1-Low (GMM)")
print("Female Hepatocytes - Selected Subtypes")
print("=" * 60)

# Re-subset from adata_pos to ensure a clean copy for DE testing
adata_hep_f_ct2_pos = adata_pos[
    adata_pos.obs["celltype2"].isin(keep_ct2)
].copy()

print(f"\n📊 Dataset Summary:")
print(f"   Total cells: {adata_hep_f_ct2_pos.n_obs:,}")
print(f"   Selected subtypes: {', '.join(keep_ct2)}")
print(f"\n📊 Ascl1_group distribution:")
print(adata_hep_f_ct2_pos.obs["Ascl1_group"].value_counts())

if "Ascl1_group" not in adata_hep_f_ct2_pos.obs.columns:
    raise ValueError("❌ 'Ascl1_group' missing. Run GMM classification first (Section 2).")

# Rename High/Low → Ascl1_high/Ascl1_low for scanpy compatibility.
# rank_genes_groups expects string group labels that work as Python identifiers.
adata_hep_f_ct2_pos.obs["Ascl1_group"] = (
    adata_hep_f_ct2_pos.obs["Ascl1_group"]
    .astype(str)
    .replace({"High": "Ascl1_high", "Low": "Ascl1_low"})
)

print("\n📊 Renamed groups (Scanpy-friendly):")
print(adata_hep_f_ct2_pos.obs["Ascl1_group"].value_counts())

# Wilcoxon rank-sum test — non-parametric, appropriate for the
# zero-inflated, non-normal distribution of scRNA-seq counts.
# use_raw=False → tests on normalized/log-transformed expression in .X.
# n_genes=all → test every gene, not just top N.
print("\n🚀 Running Wilcoxon DE test (Ascl1_high vs Ascl1_low) …")

sc.tl.rank_genes_groups(
    adata_hep_f_ct2_pos,
    groupby="Ascl1_group",
    groups=["Ascl1_high"],          # test group
    reference="Ascl1_low",          # reference group
    method="wilcoxon",              # non-parametric rank-sum
    use_raw=False,                  # use normalized expression in .X
    n_genes=adata_hep_f_ct2_pos.shape[1],  # test all genes
)
print("✔️ DE test complete.")

sc.pl.rank_genes_groups(adata_hep_f_ct2_pos, n_genes=20, sharey=False, show=True)

de_res = sc.get.rank_genes_groups_df(adata_hep_f_ct2_pos, group="Ascl1_high")

# ── DE summary ───────────────────────────────────────────────────────────────
# adj p < 0.05: Benjamini-Hochberg FDR control, standard for genome-wide tests.
# |logFC| > 0.5: a moderate effect-size filter to highlight strong changes.
print("\n" + "=" * 60)
print("DE RESULTS SUMMARY")
print("=" * 60)

sig_genes  = de_res[de_res["pvals_adj"] < 0.05]
up_genes   = sig_genes[sig_genes["logfoldchanges"] > 0]
down_genes = sig_genes[sig_genes["logfoldchanges"] < 0]

up_strong   = up_genes[up_genes["logfoldchanges"] > 0.5]
down_strong = down_genes[down_genes["logfoldchanges"] < -0.5]

print(f"\n📊 Overall DE Statistics:")
print(f"   Total genes tested: {len(de_res):,}")
print(f"   Significant genes (adj p < 0.05): {len(sig_genes):,} "
      f"({100 * len(sig_genes) / len(de_res):.1f}%)")
print(f"   Upregulated in Ascl1-High: {len(up_genes):,} "
      f"({100 * len(up_genes) / len(sig_genes):.1f}%)")
print(f"   Downregulated in Ascl1-High: {len(down_genes):,} "
      f"({100 * len(down_genes) / len(sig_genes):.1f}%)")

print(f"\n📊 Strong Effect Genes (|logFC| > 0.5):")
print(f"   Upregulated: {len(up_strong):,}")
print(f"   Downregulated: {len(down_strong):,}")

print(f"\n📊 Top 15 Upregulated Genes (Ascl1-High vs Ascl1-Low):")
top_up = up_genes.nlargest(15, "scores")[["names", "scores", "logfoldchanges", "pvals_adj"]]
top_up.columns = ["Gene", "Score", "logFC", "adj_pval"]
print(top_up.to_string(index=False))

print(f"\n📊 Top 15 Downregulated Genes (Ascl1-High vs Ascl1-Low):")
top_down = down_genes.nsmallest(15, "scores")[["names", "scores", "logfoldchanges", "pvals_adj"]]
top_down.columns = ["Gene", "Score", "logFC", "adj_pval"]
print(top_down.to_string(index=False))

# ── Save ─────────────────────────────────────────────────────────────────────
de_res.to_csv(res_dir / "DE_Ascl1_GMM_high_vs_low_female_hep_CT2subset.csv", index=False)
sig_genes.to_csv(res_dir / "DE_Ascl1_GMM_high_vs_low_female_hep_CT2subset_significant.csv", index=False)
top_up.to_csv(res_dir / "DE_Ascl1_GMM_top15_upregulated.csv", index=False)
top_down.to_csv(res_dir / "DE_Ascl1_GMM_top15_downregulated.csv", index=False)
print(f"\n💾 Saved DE results → {res_dir}/")
print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5 — GSEA: Reactome Pathways 2024
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("GSEA: Ascl1-High vs Ascl1-Low (GMM)")
print("Female Hepatocytes - Selected Subtypes")
print("Reactome 2024 - ALL RANKED GENES (NO SIGNIFICANCE FILTER)")
print("=" * 60)

csv_path = res_dir / "DE_Ascl1_GMM_high_vs_low_female_hep_CT2subset.csv"
results_df = pd.read_csv(csv_path)

if "names" in results_df.columns:
    results_df = results_df.rename(columns={"names": "gene"})
results_df["gene"] = results_df["gene"].astype(str)

print(f"\n📊 DE Results Loaded:")
print(f"   File: {csv_path}")
print(f"   Total genes: {len(results_df):,}")

# Rank ALL genes by the Wilcoxon z-score ("scores"), not just significant ones.
# GSEA is designed to work with the full ranked list — pre-filtering by
# significance destroys the statistical framework and inflates false positives.
results_df["Score"] = pd.to_numeric(results_df["scores"], errors="coerce")

rnk = (
    results_df[["gene", "Score"]]
    .dropna()
    .sort_values("Score", ascending=False)
    .copy()
)

# Convert to uppercase: Reactome uses human gene symbols (uppercase)
# while our mouse data uses Title Case (e.g., Ascl1 → ASCL1).
rnk["gene"] = rnk["gene"].str.upper()

print(f"\n📊 Ranking Summary:")
print(f"   Total ranked genes: {rnk.shape[0]:,}")
print(f"   Score range: [{rnk['Score'].min():.2f}, {rnk['Score'].max():.2f}]")
print(f"   Positive scores (up in High): {(rnk['Score'] > 0).sum():,}")
print(f"   Negative scores (down in High): {(rnk['Score'] < 0).sum():,}")

print(f"\n📊 Top 5 Ranked Genes:")
print(rnk.head().to_string(index=False))

print(f"\n📊 Bottom 5 Ranked Genes:")
print(rnk.tail().to_string(index=False))

# Reactome_Pathways_2024 — curated biological pathways from reactome.org.
# min_size=2: include small pathways (important for specialized liver functions).
# max_size=2000: include broad pathways like "Metabolism".
# permutation_num=1000: balances statistical accuracy with runtime (~2-5 min).
# seed=42: ensures reproducibility across runs.
print("\n🚀 Running Reactome 2024 GSEA …")

try:
    gsea_results = gp.prerank(
        rnk=rnk,
        gene_sets="Reactome_Pathways_2024",
        permutation_num=1000,
        min_size=2,
        max_size=2000,
        seed=42,
        verbose=True,
        outdir=None,
    )
    print("\n✔️ Reactome GSEA completed successfully.")
except Exception as e:
    print(f"[ERROR] GSEA failed: {e}")
    raise SystemExit

gsea_df = gsea_results.res2d.copy()

# ── Clean columns ────────────────────────────────────────────────────────────
gsea_df["FDR q-val"] = pd.to_numeric(gsea_df["FDR q-val"], errors="coerce")
gsea_df["NES"] = pd.to_numeric(gsea_df["NES"], errors="coerce")
gsea_df["NOM p-val"] = pd.to_numeric(gsea_df["NOM p-val"], errors="coerce")

if "Gene %" in gsea_df.columns:
    gsea_df["Gene %"] = (
        gsea_df["Gene %"].astype(str)
        .str.replace("%", "", regex=False)
        .astype(float)
    )
else:
    gsea_df["Gene %"] = np.nan

# ── GSEA summary ─────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("GSEA RESULTS SUMMARY")
print("=" * 60)

total_pathways = len(gsea_df)
sig_nom = gsea_df[gsea_df["NOM p-val"] < 0.05]
sig_fdr = gsea_df[gsea_df["FDR q-val"] < 0.25]

pos_nes = gsea_df[gsea_df["NES"] > 0]
neg_nes = gsea_df[gsea_df["NES"] < 0]
pos_sig = sig_nom[sig_nom["NES"] > 0]
neg_sig = sig_nom[sig_nom["NES"] < 0]

print(f"\n📊 Overall GSEA Statistics:")
print(f"   Total pathways tested: {total_pathways:,}")
print(f"   Positive NES (enriched in Ascl1-High): {len(pos_nes):,}")
print(f"   Negative NES (enriched in Ascl1-Low): {len(neg_nes):,}")

print(f"\n📊 Significant Pathways:")
print(f"   NOM p < 0.05: {len(sig_nom):,} ({100 * len(sig_nom) / total_pathways:.1f}%)")
print(f"      - Positive NES: {len(pos_sig):,}")
print(f"      - Negative NES: {len(neg_sig):,}")
print(f"   FDR q < 0.25: {len(sig_fdr):,} ({100 * len(sig_fdr) / total_pathways:.1f}%)")

print(f"\n📊 Top 10 Pathways Enriched in Ascl1-High (Positive NES):")
top_pos = pos_nes.nlargest(10, "NES")[["Term", "NES", "NOM p-val", "FDR q-val"]]
print(top_pos.to_string(index=False))

print(f"\n📊 Top 10 Pathways Enriched in Ascl1-Low (Negative NES):")
top_neg = neg_nes.nsmallest(10, "NES")[["Term", "NES", "NOM p-val", "FDR q-val"]]
print(top_neg.to_string(index=False))
print("\n" + "=" * 60)

# ── Save ─────────────────────────────────────────────────────────────────────
out_file = res_dir / "GSEA_Ascl1_GMM_high_vs_low_female_hep_CT2subset_Reactome2024.csv"
gsea_df.to_csv(out_file, index=False)
print(f"\n💾 Saved: {out_file}")

sig_nom.to_csv(res_dir / "GSEA_Ascl1_GMM_significant_NOMp05_Reactome2024.csv", index=False)
print(f"💾 Saved: {res_dir}/GSEA_Ascl1_GMM_significant_NOMp05_Reactome2024.csv")
print("✅ GSEA analysis completed.")
print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6 — GSEA Dot Plots: Top 30 Positive NES + Top 30 Negative NES
# ═══════════════════════════════════════════════════════════════════════════════
# Two separate dot plots for the two enrichment directions:
#   Plot A — NES > 0: pathways enriched in Ascl1-HIGH cells
#   Plot B — NES < 0: pathways enriched in Ascl1-LOW cells
# Both filtered by NOM p-val < 0.05, ranked by Gene % (pathway overlap).

print("\n" + "=" * 60)
print("GSEA DOT PLOTS: Top 30 Positive NES + Top 30 Negative NES")
print("=" * 60)

path = res_dir / "GSEA_Ascl1_GMM_high_vs_low_female_hep_CT2subset_Reactome2024.csv"
gsea = pd.read_csv(path)
gsea.columns = gsea.columns.str.strip()

if "Gene %" in gsea.columns:
    gsea["Gene %"] = (
        gsea["Gene %"].astype(str)
        .str.replace("%", "", regex=False)
        .astype(float)
    )
else:
    gsea["Gene %"] = np.nan

# Clean pathway names (strip GO identifiers if present)
gsea["term_clean"] = gsea["Term"].apply(
    lambda t: re.sub(r"\(GO:\d+\)", "", str(t)).strip()
)

# ──────────────────────────────────────────────────────────────────────────────
# PLOT A — Top 30 Positive NES (enriched in Ascl1-High)
# ──────────────────────────────────────────────────────────────────────────────

filtered_pos = gsea[(gsea["NES"] > 0) & (gsea["NOM p-val"] < 0.05)].copy()
top30_pos = filtered_pos.sort_values("Gene %", ascending=False).head(30)
print(f"\n✅ Positive NES: {top30_pos.shape[0]} pathways (NES > 0, nom p < 0.05)")

# Dot size = −log10(NOM p-val): larger dots = more significant (smaller p).
min_s, max_s = 60, 400
top30_pos["pval_size"] = -np.log10(top30_pos["NOM p-val"].replace(0, 1e-10))
pmin, pmax = top30_pos["pval_size"].min(), top30_pos["pval_size"].max()
top30_pos["size_scaled"] = (
    min_s + (top30_pos["pval_size"] - pmin) / max(pmax - pmin, 1e-9) * (max_s - min_s)
)

# Sort by NES (highest at top of y-axis)
top30_pos = top30_pos.sort_values("NES", ascending=False)
top30_pos["term_clean"] = pd.Categorical(
    top30_pos["term_clean"], categories=top30_pos["term_clean"], ordered=True
)

nes_min_p, nes_max_p = top30_pos["NES"].min(), top30_pos["NES"].max()

plt.figure(figsize=(14, 7))
ax = sns.scatterplot(
    data=top30_pos, x="NES", y="term_clean",
    size="pval_size", hue="Gene %",
    palette="RdYlBu_r", sizes=(min_s, max_s),
    edgecolor="black", linewidth=0.6,
)

# You can manually override if pathways cluster tightly:
# ax.set_xlim(1.05, 1.9)
ax.set_xlim(nes_min_p - 0.05, nes_max_p + 0.05)

plt.axvline(0, color="gray", lw=1)
plt.xlabel("Normalized Enrichment Score (NES)", fontsize=12, weight="bold")
plt.ylabel("Reactome Pathway", fontsize=12, weight="bold")
plt.title(
    f"Top 30 Reactome Pathways — Enriched in Ascl1-High (NES > 0)\n"
    f"Female Hepatocyte CT2 Subset (GMM) • "
    f"NES range: {nes_min_p:.2f} → {nes_max_p:.2f}",
    fontsize=14, weight="bold",
)

norm = plt.Normalize(top30_pos["Gene %"].min(), top30_pos["Gene %"].max())
sm = plt.cm.ScalarMappable(cmap="RdYlBu_r", norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax)
cbar.set_label("Gene %", fontsize=11, weight="bold")

ax.legend(title="−log10(NOM p-val)", bbox_to_anchor=(1.45, 1),
          loc="upper left", frameon=True, fontsize=9, title_fontsize=10)

plt.tight_layout()
plt.savefig(fig_dir / "GSEA_GMM_top30_positiveNES_female_hep_CT2subset.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/GSEA_GMM_top30_positiveNES_female_hep_CT2subset.pdf")


# ──────────────────────────────────────────────────────────────────────────────
# PLOT B — Top 30 Negative NES (enriched in Ascl1-Low)
# ──────────────────────────────────────────────────────────────────────────────

filtered_neg = gsea[(gsea["NES"] < 0) & (gsea["NOM p-val"] < 0.05)].copy()
top30_neg = filtered_neg.sort_values("Gene %", ascending=False).head(30)
print(f"\n✅ Negative NES: {top30_neg.shape[0]} pathways (NES < 0, nom p < 0.05)")

# Same size encoding as Plot A
min_s, max_s = 60, 400
top30_neg["pval_size"] = -np.log10(top30_neg["NOM p-val"].replace(0, 1e-10))
pmin, pmax = top30_neg["pval_size"].min(), top30_neg["pval_size"].max()
top30_neg["size_scaled"] = (
    min_s + (top30_neg["pval_size"] - pmin) / max(pmax - pmin, 1e-9) * (max_s - min_s)
)

# Sort by NES (most negative at bottom of y-axis)
top30_neg = top30_neg.sort_values("NES", ascending=False)
top30_neg["term_clean"] = pd.Categorical(
    top30_neg["term_clean"], categories=top30_neg["term_clean"], ordered=True
)

nes_min_n, nes_max_n = top30_neg["NES"].min(), top30_neg["NES"].max()

plt.figure(figsize=(14, 7))
ax = sns.scatterplot(
    data=top30_neg, x="NES", y="term_clean",
    size="pval_size", hue="Gene %",
    palette="RdYlBu_r", sizes=(min_s, max_s),
    edgecolor="black", linewidth=0.6,
)

# You can manually override if pathways cluster tightly:
# ax.set_xlim(-1.25, -1.07)
ax.set_xlim(nes_min_n - 0.05, nes_max_n + 0.05)

plt.axvline(0, color="gray", lw=1)
plt.xlabel("Normalized Enrichment Score (NES)", fontsize=12, weight="bold")
plt.ylabel("Reactome Pathway", fontsize=12, weight="bold")
plt.title(
    f"Top 30 Reactome Pathways — Enriched in Ascl1-Low (NES < 0)\n"
    f"Female Hepatocyte CT2 Subset (GMM) • "
    f"NES range: {nes_min_n:.2f} → {nes_max_n:.2f}",
    fontsize=14, weight="bold",
)

norm = plt.Normalize(top30_neg["Gene %"].min(), top30_neg["Gene %"].max())
sm = plt.cm.ScalarMappable(cmap="RdYlBu_r", norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax)
cbar.set_label("Gene %", fontsize=11, weight="bold")

ax.legend(title="−log10(NOM p-val)", bbox_to_anchor=(1.45, 1),
          loc="upper left", frameon=True, fontsize=9, title_fontsize=10)

plt.tight_layout()
plt.savefig(fig_dir / "GSEA_GMM_top30_negativeNES_female_hep_CT2subset.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/GSEA_GMM_top30_negativeNES_female_hep_CT2subset.pdf")


print("\n" + "=" * 60)
print("🎉  ALL SECTIONS COMPLETE")
print("=" * 60)
