#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ascl1_liver_aging_analysis.py
==============================
Ascl1 expression analysis in murine liver aging (single-cell multiome RNA).

Sections
--------
1. Load data
2. Global Ascl1 profiling (sex / age / celltype)
3. Female-only Ascl1 analysis
4. Female hepatocyte Ascl1 analysis (age / celltype2)
5. Count-based dot plots (Seaborn)
6. Ascl1+ subset deep characterization
7. Differential expression — Ascl1+ vs Ascl1− (Wilcoxon)
8. Volcano plot with functional gene annotations
9. GSEA — Reactome Pathways 2024
10. GSEA dot plot
"""

import re
import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt
import seaborn as sns
import gseapy as gp
from matplotlib.patches import Patch
from pathlib import Path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — Load Data
# ═══════════════════════════════════════════════════════════════════════════════

# Path to the WNN-integrated single-cell RNA object (h5ad format).
# This object was generated by the ArchR preprocessing pipeline (Step 1)
# followed by schard h5ad conversion. It contains cells from 5 age groups
# across both sexes, with broad celltype and hepatocyte sub-classifications.
h5ad_path = "/data/sarkern2/multiome_liver/final_object/final_rna_wnn.h5ad"

# Output directories — created automatically if missing
fig_dir = Path("figures")
res_dir = Path("results")
fig_dir.mkdir(exist_ok=True)
res_dir.mkdir(exist_ok=True)

print("Loading data …")
adata = sc.read_h5ad(h5ad_path)
print(f"Loaded {adata.n_obs:,} cells × {adata.n_vars:,} genes")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — Global Ascl1 Profiling (All Cells)
# ═══════════════════════════════════════════════════════════════════════════════

# Age groups are ordered biologically: young → mid_age → old → pre_geriatric → geriatric.
# This ordering ensures dot plots and summaries follow the aging trajectory.
age_order = ["young", "mid_age", "old", "pre_geriatric", "geriatric"]
age_order_filtered = [a for a in age_order if a in adata.obs["age"].unique()]
adata.obs["age"] = adata.obs["age"].astype(
    pd.CategoricalDtype(categories=age_order_filtered, ordered=True)
)

# Extract Ascl1 normalized expression.
# Cells with expression > 0 are classified as Ascl1-positive (Ascl1+).
gene = "Ascl1"
expr = adata[:, gene].X
expr = expr.toarray().ravel() if not isinstance(expr, np.ndarray) else expr.ravel()
adata.obs["Ascl1_expr"] = expr
adata.obs["Ascl1_positive"] = adata.obs["Ascl1_expr"] > 0

# ── Summary statistics ───────────────────────────────────────────────────────
print("=" * 60)
print("ASCL1 EXPRESSION SUMMARY")
print("=" * 60)

total_cells = adata.n_obs
ascl1_pos = adata.obs["Ascl1_positive"].sum()
print(f"\n📊 Overall:")
print(f"   Total cells: {total_cells:,}")
print(f"   Ascl1+ cells: {ascl1_pos:,} ({100 * ascl1_pos / total_cells:.1f}%)")

print(f"\n📊 By Sex:")
sex_summary = adata.obs.groupby("sex").agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
sex_summary["pct_positive"] = 100 * sex_summary["positive"] / sex_summary["total"]
print(sex_summary.to_string(index=False))

print(f"\n📊 By Age:")
age_summary = adata.obs.groupby("age", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_summary["pct_positive"] = 100 * age_summary["positive"] / age_summary["total"]
print(age_summary.to_string(index=False))

print(f"\n📊 By Celltype:")
ct_summary = adata.obs.groupby("celltype", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
ct_summary["pct_positive"] = 100 * ct_summary["positive"] / ct_summary["total"]
ct_summary = ct_summary.sort_values("pct_positive", ascending=False)
print(ct_summary.to_string(index=False))

print(f"\n📊 By Sex × Age:")
sex_age_summary = adata.obs.groupby(["sex", "age"], observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
sex_age_summary["pct_positive"] = 100 * sex_age_summary["positive"] / sex_age_summary["total"]
print(sex_age_summary.to_string(index=False))
print("\n" + "=" * 60)

# ── 3-panel dot plot: Sex → Age → Celltype ───────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(13, 4))

sc.pl.dotplot(adata, var_names=["Ascl1"], groupby="sex",
              ax=axes[0], show=False, cmap="Reds")
axes[0].set_title("Ascl1 by Sex")

sc.pl.dotplot(adata, var_names=["Ascl1"], groupby="age",
              ax=axes[1], show=False, cmap="Reds")
axes[1].set_title("Ascl1 by Age (Male and Female)")

sc.pl.dotplot(adata, var_names=["Ascl1"], groupby="celltype",
              ax=axes[2], show=False, cmap="Reds")
axes[2].set_title("Ascl1 by Celltype - Male and Female")

plt.tight_layout()
plt.savefig(fig_dir / "Ascl1_dotplots_all_sex_age_celltype.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/Ascl1_dotplots_all_sex_age_celltype.pdf")

# ── Save CSVs ────────────────────────────────────────────────────────────────
sex_summary.to_csv(res_dir / "Ascl1_summary_by_sex.csv", index=False)
age_summary.to_csv(res_dir / "Ascl1_summary_by_age.csv", index=False)
ct_summary.to_csv(res_dir / "Ascl1_summary_by_celltype.csv", index=False)
sex_age_summary.to_csv(res_dir / "Ascl1_summary_by_sex_age.csv", index=False)
print("Saved summary CSVs → results/")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — Female-Only Ascl1 Analysis
# ═══════════════════════════════════════════════════════════════════════════════

adata_f = adata[adata.obs["sex"] == "female"].copy()

print("\n" + "=" * 60)
print("FEMALE-ONLY ASCL1 ANALYSIS")
print("=" * 60)
print(f"\nCells after female subset: {adata_f.n_obs:,}")

# Re-extract expression for the subset (sparse matrix rows change after copy)
expr = adata_f[:, "Ascl1"].X
expr = expr.toarray().ravel() if not isinstance(expr, np.ndarray) else expr.ravel()
adata_f.obs["Ascl1_expr"] = expr
adata_f.obs["Ascl1_positive"] = adata_f.obs["Ascl1_expr"] > 0

age_order_filtered = [a for a in age_order if a in adata_f.obs["age"].unique()]
adata_f.obs["age"] = adata_f.obs["age"].astype(
    pd.CategoricalDtype(categories=age_order_filtered, ordered=True)
)

total_cells = adata_f.n_obs
ascl1_pos = adata_f.obs["Ascl1_positive"].sum()
print(f"\n📊 Overall (Female):")
print(f"   Total cells: {total_cells:,}")
print(f"   Ascl1+ cells: {ascl1_pos:,} ({100 * ascl1_pos / total_cells:.1f}%)")

print(f"\n📊 By Age (Female):")
age_summary_f = adata_f.obs.groupby("age", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_summary_f["pct_positive"] = 100 * age_summary_f["positive"] / age_summary_f["total"]
print(age_summary_f.to_string(index=False))

print(f"\n📊 By Celltype (Female):")
ct_summary_f = adata_f.obs.groupby("celltype", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
ct_summary_f["pct_positive"] = 100 * ct_summary_f["positive"] / ct_summary_f["total"]
ct_summary_f = ct_summary_f.sort_values("pct_positive", ascending=False)
print(ct_summary_f.to_string(index=False))

print(f"\n📊 By Age × Celltype (Female, top 10 by Ascl1+ count):")
age_ct_f = adata_f.obs.groupby(["age", "celltype"], observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_ct_f["pct_positive"] = 100 * age_ct_f["positive"] / age_ct_f["total"]
print(age_ct_f.sort_values("positive", ascending=False).head(10).to_string(index=False))
print("\n" + "=" * 60)

# ── 2-panel dot plot ─────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(10, 4))

sc.pl.dotplot(adata_f, var_names=["Ascl1"], groupby="age",
              ax=axes[0], show=False, cmap="Reds")
axes[0].set_title("Ascl1 by Age (Female only)")

sc.pl.dotplot(adata_f, var_names=["Ascl1"], groupby="celltype",
              ax=axes[1], show=False, cmap="Reds")
axes[1].set_title("Ascl1 by Cell Type (Female only)")

plt.tight_layout()
plt.savefig(fig_dir / "Ascl1_dotplots_female_only_age_celltype.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/Ascl1_dotplots_female_only_age_celltype.pdf")

age_summary_f.to_csv(res_dir / "Ascl1_summary_female_by_age.csv", index=False)
ct_summary_f.to_csv(res_dir / "Ascl1_summary_female_by_celltype.csv", index=False)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4 — Female Hepatocyte Ascl1 Analysis (Age + Celltype2)
# ═══════════════════════════════════════════════════════════════════════════════

adata_fh = adata[
    (adata.obs["sex"] == "female") &
    (adata.obs["celltype"] == "Hepatocyte")
].copy()

print("\n" + "=" * 60)
print("FEMALE HEPATOCYTE ASCL1 ANALYSIS")
print("=" * 60)
print(f"\nCells after female + hepatocyte subset: {adata_fh.n_obs:,}")

expr = adata_fh[:, "Ascl1"].X
expr = expr.toarray().ravel() if not isinstance(expr, np.ndarray) else expr.ravel()
adata_fh.obs["Ascl1_expr"] = expr
adata_fh.obs["Ascl1_positive"] = adata_fh.obs["Ascl1_expr"] > 0

age_order_filtered = [a for a in age_order if a in adata_fh.obs["age"].unique()]
adata_fh.obs["age"] = adata_fh.obs["age"].astype(
    pd.CategoricalDtype(categories=age_order_filtered, ordered=True)
)

total_cells = adata_fh.n_obs
ascl1_pos = adata_fh.obs["Ascl1_positive"].sum()
print(f"\n📊 Overall (Female Hepatocytes):")
print(f"   Total cells: {total_cells:,}")
print(f"   Ascl1+ cells: {ascl1_pos:,} ({100 * ascl1_pos / total_cells:.1f}%)")

print(f"\n📊 By Age (Female Hepatocytes):")
age_summary_fh = adata_fh.obs.groupby("age", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_summary_fh["pct_positive"] = 100 * age_summary_fh["positive"] / age_summary_fh["total"]
print(age_summary_fh.to_string(index=False))

print(f"\n📊 By Celltype2 (Female Hepatocytes):")
ct2_summary = adata_fh.obs.groupby("celltype2", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
ct2_summary["pct_positive"] = 100 * ct2_summary["positive"] / ct2_summary["total"]
ct2_summary = ct2_summary.sort_values("pct_positive", ascending=False)
print(ct2_summary.to_string(index=False))

print(f"\n📊 By Age × Celltype2 (Female Hepatocytes, top 15 by Ascl1+ count):")
age_ct2 = adata_fh.obs.groupby(["age", "celltype2"], observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_ct2["pct_positive"] = 100 * age_ct2["positive"] / age_ct2["total"]
print(age_ct2.sort_values("positive", ascending=False).head(15).to_string(index=False))
print("\n" + "=" * 60)

# ── 2-panel dot plot: Age → Celltype2 ────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(10, 4))

sc.pl.dotplot(adata_fh, var_names=["Ascl1"], groupby="age",
              ax=axes[0], show=False, cmap="Reds")
axes[0].set_title("Ascl1 by Age (Female Hepatocytes only)")

if "celltype2" not in adata_fh.obs.columns:
    raise ValueError("adata.obs does not contain 'celltype2' column!")

sc.pl.dotplot(adata_fh, var_names=["Ascl1"], groupby="celltype2",
              ax=axes[1], show=False, cmap="Reds")
axes[1].set_title("Ascl1 by Celltype2 (Female Hepatocytes only)")

plt.tight_layout()
plt.savefig(fig_dir / "Ascl1_dotplots_female_hepatocyte_age_celltype2.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/Ascl1_dotplots_female_hepatocyte_age_celltype2.pdf")

age_summary_fh.to_csv(res_dir / "Ascl1_summary_female_hep_by_age.csv", index=False)
ct2_summary.to_csv(res_dir / "Ascl1_summary_female_hep_by_celltype2.csv", index=False)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5 — Count-Based Dot Plots (Seaborn)
# ═══════════════════════════════════════════════════════════════════════════════
# Standard scanpy dotplots show fraction-expressing + mean expression.
# These count dotplots instead show absolute Ascl1+ cell numbers per group,
# which is important when cell counts vary dramatically across age groups.

# Reverse the age order so geriatric is at the top of the y-axis
# and young is at the bottom — visually emphasizing the aging trajectory
# when reading top-to-bottom.
age_order_rev = ["geriatric", "pre_geriatric", "old", "mid_age", "young"]
age_order_rev_filtered = [a for a in age_order_rev if a in adata_fh.obs["age"].unique()]
adata_fh.obs["age"] = adata_fh.obs["age"].astype(
    pd.CategoricalDtype(categories=age_order_rev_filtered, ordered=True)
)

age_counts = (
    adata_fh.obs.groupby("age")["Ascl1_positive"]
    .sum().reset_index(name="Ascl1_count")
)
ct2_counts = (
    adata_fh.obs.groupby("celltype2")["Ascl1_positive"]
    .sum().reset_index(name="Ascl1_count")
)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))

# Panel 1 — Age
sns.scatterplot(
    data=age_counts,
    x=["Ascl1"] * len(age_counts), y="age",
    size="Ascl1_count", hue="Ascl1_count",
    palette="Reds", sizes=(50, 600),
    edgecolor="black", linewidth=0.6, ax=axes[0],
)
axes[0].set_title("Ascl1⁺ Count — Age / Hep_Female", weight="bold", fontsize=12)
axes[0].set_xlabel("Ascl1 (Count Dotplot)")
axes[0].set_ylabel("Age")
axes[0].invert_yaxis()
axes[0].legend_.remove()
axes[0].legend(title="Ascl1+ Count", loc="center left",
               bbox_to_anchor=(1.15, 0.5), frameon=True, fontsize=9, title_fontsize=10)

# Panel 2 — Celltype2
sns.scatterplot(
    data=ct2_counts,
    x=["Ascl1"] * len(ct2_counts), y="celltype2",
    size="Ascl1_count", hue="Ascl1_count",
    palette="Reds", sizes=(50, 600),
    edgecolor="black", linewidth=0.6, ax=axes[1],
)
axes[1].set_title("Ascl1⁺ Count — Celltype2 / Hep_Female", weight="bold", fontsize=12)
axes[1].set_xlabel("Ascl1 (Count Dotplot)")
axes[1].set_ylabel("Celltype2")
axes[1].legend_.remove()
axes[1].legend(title="Ascl1+ Count", loc="center left",
               bbox_to_anchor=(1.15, 0.5), frameon=True, fontsize=9, title_fontsize=10)

plt.tight_layout()
plt.savefig(fig_dir / "Ascl1_count_dotplots_female_hepatocyte.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/Ascl1_count_dotplots_female_hepatocyte.pdf")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6 — Ascl1+ Subset Deep Characterization
# ═══════════════════════════════════════════════════════════════════════════════
# Re-subset fresh from the full object so age ordering is clean (young → geriatric).

adata_fh = adata[
    (adata.obs["sex"].astype(str) == "female") &
    (adata.obs["celltype"].astype(str) == "Hepatocyte")
].copy()

assert adata_fh.n_obs > 0
assert "Ascl1" in adata_fh.var_names

expr = adata_fh[:, "Ascl1"].X.toarray().ravel()
adata_fh.obs["Ascl1_expr"] = expr
adata_fh.obs["Ascl1_positive"] = adata_fh.obs["Ascl1_expr"] > 0

adata_fh_pos = adata_fh[adata_fh.obs["Ascl1_positive"]].copy()

print("\n" + "=" * 60)
print("FEMALE HEPATOCYTE ASCL1 SUBSET ANALYSIS")
print("=" * 60)
print(f"\nTotal female hepatocytes: {adata_fh.n_obs:,}")
print(f"Ascl1+ cells: {adata_fh_pos.n_obs:,}")
print(f"Ascl1+ fraction: {adata_fh_pos.n_obs / adata_fh.n_obs:.3f} "
      f"({100 * adata_fh_pos.n_obs / adata_fh.n_obs:.1f}%)")

print(f"\n📊 Ascl1+ by Age:")
age_summary_fh2 = adata_fh.obs.groupby("age", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
age_summary_fh2["pct_positive"] = 100 * age_summary_fh2["positive"] / age_summary_fh2["total"]
print(age_summary_fh2.to_string(index=False))

print(f"\n📊 Ascl1+ by Celltype2:")
ct2_summary2 = adata_fh.obs.groupby("celltype2", observed=True).agg(
    total=("Ascl1_positive", "size"),
    positive=("Ascl1_positive", "sum"),
    mean_expr=("Ascl1_expr", "mean"),
).reset_index()
ct2_summary2["pct_positive"] = 100 * ct2_summary2["positive"] / ct2_summary2["total"]
ct2_summary2 = ct2_summary2.sort_values("pct_positive", ascending=False)
print(ct2_summary2.to_string(index=False))

print(f"\n📊 Ascl1 Expression (Ascl1+ cells only):")
print(f"   Mean:   {adata_fh_pos.obs['Ascl1_expr'].mean():.3f}")
print(f"   Median: {adata_fh_pos.obs['Ascl1_expr'].median():.3f}")
print(f"   Std:    {adata_fh_pos.obs['Ascl1_expr'].std():.3f}")
print(f"   Min:    {adata_fh_pos.obs['Ascl1_expr'].min():.3f}")
print(f"   Max:    {adata_fh_pos.obs['Ascl1_expr'].max():.3f}")

print(f"\n📊 Ascl1+ Cell Distribution by Age:")
age_dist = adata_fh_pos.obs["age"].value_counts()
age_dist_pct = 100 * age_dist / adata_fh_pos.n_obs
age_dist_df = pd.DataFrame({
    "age": age_dist.index, "count": age_dist.values,
    "pct_of_Ascl1_pos": age_dist_pct.values,
})
print(age_dist_df.to_string(index=False))

print(f"\n📊 Ascl1+ Cell Distribution by Celltype2:")
ct2_dist = adata_fh_pos.obs["celltype2"].value_counts()
ct2_dist_pct = 100 * ct2_dist / adata_fh_pos.n_obs
ct2_dist_df = pd.DataFrame({
    "celltype2": ct2_dist.index, "count": ct2_dist.values,
    "pct_of_Ascl1_pos": ct2_dist_pct.values,
})
print(ct2_dist_df.to_string(index=False))
print("\n" + "=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 7 — Differential Expression: Ascl1+ vs Ascl1− (Wilcoxon)
# ═══════════════════════════════════════════════════════════════════════════════

assert "Ascl1" in adata_fh.var_names, "Ascl1 not found in var_names"

print("\n" + "=" * 60)
print("DIFFERENTIAL EXPRESSION: Ascl1+ vs Ascl1- (Female Hepatocytes)")
print("=" * 60)

ascl1_expr = adata_fh[:, "Ascl1"].X.toarray().ravel()
adata_fh.obs["Ascl1_status"] = pd.Categorical(
    np.where(ascl1_expr > 0, "Ascl1_pos", "Ascl1_neg"),
    categories=["Ascl1_pos", "Ascl1_neg"],
    ordered=True,
)

print(f"\n📊 Group Sizes:")
print(adata_fh.obs["Ascl1_status"].value_counts())
print(f"\nAscl1-positive fraction: {(ascl1_expr > 0).mean():.3f} "
      f"({100 * (ascl1_expr > 0).mean():.1f}%)")

# Wilcoxon rank-sum test — a non-parametric test chosen because single-cell
# expression data is zero-inflated and non-normally distributed.
# use_raw=False → uses the normalized/log-transformed counts in adata.X
print("\n🚀 Running Wilcoxon DE test (Ascl1_pos vs Ascl1_neg) …")
sc.tl.rank_genes_groups(
    adata_fh,
    groupby="Ascl1_status",
    groups=["Ascl1_pos"],       # test group
    reference="Ascl1_neg",      # reference group
    method="wilcoxon",          # non-parametric rank-sum
    use_raw=False,              # use normalized expression in .X
)
print("✔️ DE test complete.")

sc.pl.rank_genes_groups(adata_fh, n_genes=20, sharey=False)

de_res = sc.get.rank_genes_groups_df(adata_fh, group="Ascl1_pos")

# Benjamini-Hochberg adjusted p-value < 0.05 is the standard threshold
# for controlling the false discovery rate in genome-wide tests.
pval_threshold = 0.05

sig_genes  = de_res[de_res["pvals_adj"] < pval_threshold]
up_genes   = sig_genes[sig_genes["logfoldchanges"] > 0]
down_genes = sig_genes[sig_genes["logfoldchanges"] < 0]

print("\n" + "=" * 60)
print("DE RESULTS SUMMARY")
print("=" * 60)
print(f"\n📊 Overall DE Statistics:")
print(f"   Total genes tested: {len(de_res):,}")
print(f"   Significant genes (adj p < {pval_threshold}): {len(sig_genes):,}")
print(f"   Upregulated in Ascl1+: {len(up_genes):,}")
print(f"   Downregulated in Ascl1+: {len(down_genes):,}")

print(f"\n📊 Top 15 Upregulated Genes (Ascl1+ vs Ascl1-):")
top_up = up_genes.nlargest(15, "scores")[["names", "scores", "logfoldchanges", "pvals_adj"]]
top_up.columns = ["Gene", "Score", "logFC", "adj_pval"]
print(top_up.to_string(index=False))

print(f"\n📊 Top 15 Downregulated Genes (Ascl1+ vs Ascl1-):")
top_down = down_genes.nsmallest(15, "scores")[["names", "scores", "logfoldchanges", "pvals_adj"]]
top_down.columns = ["Gene", "Score", "logFC", "adj_pval"]
print(top_down.to_string(index=False))

de_res.to_csv(res_dir / "wilcoxon_Ascl1_pos_vs_neg_female_hepatocytes.csv", index=False)
sig_genes.to_csv(res_dir / "wilcoxon_Ascl1_pos_vs_neg_female_hepatocytes_significant.csv", index=False)
print(f"\n💾 Saved DE results → {res_dir}/")
print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 8 — Volcano Plot
# ═══════════════════════════════════════════════════════════════════════════════

de_res = pd.read_csv(res_dir / "wilcoxon_Ascl1_pos_vs_neg_female_hepatocytes.csv")

# Epsilon prevents -log10(0) = inf for genes with extremely small p-values.
epsilon = 1e-300
de_res["pvals_adj_safe"] = de_res["pvals_adj"] + epsilon

de_res["-log10_pval"]     = -np.log10(de_res["pvals"] + epsilon)
de_res["-log10_pval_adj"] = -np.log10(de_res["pvals_adj_safe"])

# Composite rank score: genes that are BOTH highly significant AND have
# large fold changes rank highest. Used to prioritize labeling.
de_res["rank_score"] = de_res["-log10_pval_adj"] * np.abs(de_res["logfoldchanges"])
de_res["rank"] = de_res["rank_score"].rank(ascending=False).astype(int)

# Significance categories.
# logfc_threshold = 0 means any direction counts — we care about statistical
# significance (adj p < 0.05) rather than imposing a fold-change cutoff,
# because biologically meaningful changes in transcription factor targets
# can be subtle.
pval_threshold = 0.05
logfc_threshold = 0

de_res["sig"] = "Not Sig"
de_res.loc[
    (de_res["pvals_adj"] < pval_threshold) &
    (de_res["logfoldchanges"] > logfc_threshold),
    "sig",
] = "Up in Ascl1+"
de_res.loc[
    (de_res["pvals_adj"] < pval_threshold) &
    (de_res["logfoldchanges"] < -logfc_threshold),
    "sig",
] = "Down in Ascl1+"

print(de_res["sig"].value_counts())

# Pink and teal color scheme: pink for upregulated matches the Ascl1+
# identity (warm/active), teal for downregulated provides strong contrast.
colors = {
    "Not Sig":        "lightgray",
    "Up in Ascl1+":   "lightpink",
    "Down in Ascl1+": "#008080",
}

fig, ax = plt.subplots(figsize=(20, 10))

for category, color in colors.items():
    sub = de_res[de_res["sig"] == category]
    ax.scatter(sub["logfoldchanges"], sub["-log10_pval_adj"],
               c=color, label=category, s=24, alpha=0.7, edgecolors="none")

ax.axhline(-np.log10(pval_threshold), color="black", ls="--", lw=0.8, alpha=0.6)
ax.axvline(0, color="black", ls="--", lw=0.8, alpha=0.6)

# ── Functional gene categories to label ──────────────────────────────────────
# These genes were selected based on literature and pathway analysis:
# - Cell Cycle (Up): Ascl1+ hepatocytes show increased proliferative markers
# - Translation (Up): mitochondrial and cytoplasmic ribosomal proteins
# - mTOR Pathway (Up): Ragulator complex subunits suggest mTOR activation
# - Immediate Early (Down): stress-response TFs are depleted in Ascl1+ cells
# - Cell Cycle (Down): checkpoint kinases Wee1/Plk3 paradoxically reduced
# - Hepatic Function (Down): core metabolic enzymes and CYPs downregulated
# - Others: receptors, secreted factors, and iron regulators of interest
genes_to_label = {
    "Cell Cycle (Up)": {
        "genes": ["Mki67", "Ccne2", "Ccnd1", "Ccnd2", "Ccng1", "Ccnf"],
        "color": "#8B0000",
    },
    "Translation (Up)": {
        "genes": ["Mrps14", "Mrps36", "Rps13", "Rpl5"],
        "color": "#4B0082",
    },
    "mTOR Pathway (Up)": {
        "genes": ["Lamtor5", "Lamtor4", "Lamtor3", "Lamtor2", "Slc38a9"],
        "color": "darkgreen",
    },
    "Immediate Early (Down)": {
        "genes": ["Jun", "Fos", "Egr1", "Jund", "Atf3"],
        "color": "#DC143C",
    },
    "Cell Cycle (Down)": {
        "genes": ["Wee1", "Plk3"],
        "color": "#FF1493",
    },
    "Hepatic Function (Down)": {
        "genes": ["Aldob", "G6pc", "Cps1", "Gys2", "Cyp2c37",
                   "Cyp2c67", "Abcc3", "Scd1", "Fasn", "Hmgcr"],
        "color": "#FF7F50",
    },
    "Others": {
        "genes": ["Lifr", "Esr1", "Angpt1", "Cd36", "Vwf",
                   "Fgl1", "Hif1a", "Hamp", "Hamp2"],
        "color": "#8B4513",
    },
}

gene_positions = []
for category, info in genes_to_label.items():
    for g in info["genes"]:
        row = de_res[de_res["names"] == g]
        if not row.empty:
            r = row.iloc[0]
            gene_positions.append({
                "gene": r["names"],
                "x": r["logfoldchanges"],
                "y": r["-log10_pval_adj"],
                "color": info["color"],
            })

# adjustText automatically repositions overlapping labels with connector
# lines — much cleaner than manual offset calculation.
try:
    from adjustText import adjust_text

    texts = []
    for pos in gene_positions:
        text = ax.text(
            pos["x"], pos["y"], pos["gene"],
            fontsize=11, fontweight="bold", color=pos["color"],
            ha="center", va="center",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                      edgecolor="none", alpha=0.85),
            zorder=10,
        )
        texts.append(text)

    adjust_text(
        texts,
        arrowprops=dict(arrowstyle="-", color="gray", lw=0.5, alpha=0.6),
        expand_points=(1.5, 1.5),
        expand_text=(1.2, 1.2),
        force_points=(0.5, 0.5),
        force_text=(0.5, 0.5),
        ax=ax,
    )
    print("Using adjustText for label placement")

except ImportError:
    print("adjustText not installed — using manual offset placement.")
    print("Install with: pip install adjustText")

    for pos in gene_positions:
        ax.annotate(
            pos["gene"], (pos["x"], pos["y"]),
            fontsize=11, fontweight="bold", color=pos["color"],
            textcoords="offset points", xytext=(0, 10), ha="center",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                      edgecolor="none", alpha=0.85),
        )

ax.set_xlim(-5, 5)
ax.set_xlabel("Log2 Fold Change (Ascl1+ vs Ascl1-)", fontsize=13, fontweight="bold")
ax.set_ylabel("-log10(Adjusted p-value)", fontsize=13, fontweight="bold")
plt.title("Differential Gene Expression: Ascl1+ vs Ascl1- Hepatocytes\n"
          "(Female, Wilcoxon rank-sum test)", fontsize=15, fontweight="bold")

# Significance legend — lower right outside plot
sig_legend = ax.legend(
    frameon=True, loc="lower right", bbox_to_anchor=(1.15, 0),
    title="Significance", fontsize=12, title_fontsize=13, markerscale=2.5,
)

# Functional category legend — upper right outside plot
functional_patches = [
    Patch(facecolor=info["color"], label=category)
    for category, info in genes_to_label.items()
]
functional_legend = ax.legend(
    handles=functional_patches, frameon=True, framealpha=0.9,
    loc="upper right", bbox_to_anchor=(1.18, 1),
    title="Functional Categories", fontsize=12, title_fontsize=13,
)
ax.add_artist(sig_legend)

plt.tight_layout()
plt.savefig(fig_dir / "volcano_Ascl1_hepatocytes.pdf", dpi=300, bbox_inches="tight")
plt.savefig(fig_dir / "volcano_Ascl1_hepatocytes.png", dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/volcano_Ascl1_hepatocytes.pdf/.png")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 9 — GSEA: Reactome Pathways 2024
# ═══════════════════════════════════════════════════════════════════════════════

csv_path = res_dir / "wilcoxon_Ascl1_pos_vs_neg_female_hepatocytes.csv"
results_df = pd.read_csv(csv_path)
results_df = results_df.rename(columns={"names": "gene"})
results_df["gene"] = results_df["gene"].astype(str)

# Rank genes by the Wilcoxon z-score ("scores" column from scanpy).
# Small random jitter (N(0, 1e-6)) breaks ties — GSEA requires unique ranks,
# and many lowly-expressed genes share identical test statistics.
results_df["Score"] = results_df["scores"] + np.random.normal(0, 1e-6, len(results_df))

rnk = results_df[["gene", "Score"]].dropna().sort_values("Score", ascending=False)

# Convert to uppercase because Reactome uses human gene symbols (uppercase),
# while the mouse data uses Title Case (e.g., Ascl1 → ASCL1).
rnk["gene"] = rnk["gene"].str.upper()

print(f"[INFO] Ranked {len(rnk)} genes for GSEA.")
print(rnk.head())

# Reactome_Pathways_2024 — curated biological pathways from reactome.org.
# min_size=2 allows even small pathways (important for specialized liver functions).
# max_size=2000 includes broad pathways like "Metabolism".
# 1000 permutations balances statistical accuracy with runtime (~2-5 min).
# seed=42 ensures reproducibility across runs.
try:
    gsea_results = gp.prerank(
        rnk=rnk,
        gene_sets="Reactome_Pathways_2024",
        permutation_num=1000,
        min_size=2,
        max_size=2000,
        seed=42,
        outdir=None,
        verbose=True,
    )
    print("[INFO] GSEA (Reactome_Pathways_2024) completed successfully.")
except Exception as e:
    print(f"[ERROR] GSEA failed: {e}")
    raise SystemExit

gsea_df = gsea_results.res2d.copy()

gsea_df["FDR q-val"] = pd.to_numeric(gsea_df["FDR q-val"], errors="coerce")
if "Gene %" in gsea_df.columns:
    gsea_df["Gene %"] = (
        gsea_df["Gene %"].astype(str)
        .str.replace("%", "", regex=False)
        .astype(float)
    )
else:
    gsea_df["Gene %"] = 1.0

print(f"[INFO] GSEA result table shape: {gsea_df.shape}")
print(gsea_df.head())

out_file = res_dir / "GSEA_Ascl1_pos_neg_female_hepatocytes_Reactome2024.csv"
gsea_df.to_csv(out_file, index=False)
print(f"[INFO] Saved {len(gsea_df)} pathways → {out_file}")
print("✅ GSEA completed successfully.")


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 10 — GSEA Dot Plot (Top 30 Reactome Pathways)
# ═══════════════════════════════════════════════════════════════════════════════

path = res_dir / "GSEA_Ascl1_pos_neg_female_hepatocytes_Reactome2024.csv"
gsea = pd.read_csv(path)
gsea.columns = gsea.columns.str.strip()

if "Gene %" in gsea.columns:
    gsea["Gene %"] = (
        gsea["Gene %"].astype(str)
        .str.replace("%", "", regex=False)
        .astype(float)
    )
else:
    gsea["Gene %"] = np.nan

# Filter to nominally significant pathways (NOM p < 0.05) and take
# the top 30 by Gene % — this prioritizes pathways with the highest
# overlap between the gene set and the ranked list, ensuring biological
# relevance rather than just statistical significance.
filtered = gsea[gsea["NOM p-val"] < 0.05].copy()
top = filtered.sort_values("Gene %", ascending=False).head(30)

print(f"✅ Selected {top.shape[0]} Reactome terms by highest Gene % (nom p < 0.05)")

# Clean pathway names (strip any GO identifiers if present)
top["term_clean"] = top["Term"].apply(
    lambda t: re.sub(r"\(GO:\d+\)", "", str(t)).strip()
)

# Dot size encodes statistical confidence: −log10(NOM p-val).
# Larger dots = more significant (smaller p-values).
top["pval_size"] = -np.log10(top["NOM p-val"].replace(0, 1e-10))

min_size, max_size = 60, 400
pmin, pmax = top["pval_size"].min(), top["pval_size"].max()
top["size_scaled"] = (
    min_size + (top["pval_size"] - pmin) / (pmax - pmin) * (max_size - min_size)
)

# Sort by NES (Normalized Enrichment Score) so the most positively/negatively
# enriched pathways appear at top/bottom of the y-axis.
top = top.sort_values("NES", ascending=False)
top["term_clean"] = pd.Categorical(
    top["term_clean"], categories=top["term_clean"], ordered=True,
)

nes_min, nes_max = top["NES"].min(), top["NES"].max()
nes_range = f"NES range: {nes_min:.2f} → {nes_max:.2f}"

# ── Plot ─────────────────────────────────────────────────────────────────────
plt.figure(figsize=(7, 9))
ax = sns.scatterplot(
    data=top, x="NES", y="term_clean",
    size="size_scaled", hue="Gene %",
    palette="RdYlBu_r", sizes=(min_size, max_size),
    edgecolor="black", linewidth=0.6,
)

# You can manually override the NES x-axis limits if needed:
# plt.xlim(-2.0, -1.1)
plt.xlim(nes_min - 0.1, nes_max + 0.1)   # auto-range based on data

plt.axvline(0, color="gray", lw=1)
plt.xlabel("Normalized Enrichment Score (NES)", fontsize=12, weight="bold")
plt.ylabel("Reactome Pathway", fontsize=12, weight="bold")
plt.title(
    f"Top 30 Reactome Pathways by Gene %\n"
    f"Ascl1-pos vs Ascl1-neg (Female Hepatocyte CT2)\n{nes_range}",
    fontsize=14, weight="bold",
)

# Colorbar — Gene % as a continuous color scale (RdYlBu_r: red = high, blue = low)
norm = plt.Normalize(top["Gene %"].min(), top["Gene %"].max())
sm = plt.cm.ScalarMappable(cmap="RdYlBu_r", norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax)
cbar.set_label("Gene %", fontsize=11, weight="bold")

ax.legend(
    title="−log10(NOM p-val)",
    bbox_to_anchor=(1.42, 1), loc="upper left",
    frameon=True, fontsize=9, title_fontsize=10,
)

plt.tight_layout()
plt.savefig(fig_dir / "GSEA_Ascl1_pos_neg_female_hepatocytes_Reactome2024.pdf",
            dpi=300, bbox_inches="tight")
plt.show()
print(f"Saved: {fig_dir}/GSEA_Ascl1_pos_neg_female_hepatocytes_Reactome2024.pdf")

print("\n" + "=" * 60)
print("🎉  ALL SECTIONS COMPLETE")
print("=" * 60)
